name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 0
          - name: 1
          - name: 2
          - name: 3
          - name: 4
          - name: 5
          - name: 6
          - name: 7
          - name: 8
          - name: 9
    steps:
      - run: sleep 60

  quad-cores:
    # https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
    name: Quad Cores
    runs-on: ubuntu-latest
    steps:
      - run: lscpu
      - run: nproc
      - run: free -h
      - run: df -h
