name: Test

on:
  workflow_dispatch:
  push:

jobs:
  macos-latest:
    name: MacOS Latest
    runs-on: macos-latest
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 0
          - name: 1
          - name: 2
          - name: 3
          - name: 4
    steps:
      - run: system_profiler
      - run: sleep 60

  quad-cores:
    # https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
    name: Quad Cores
    runs-on: ubuntu-latest
    steps:
      - run: lscpu
      - run: echo $PWD
      - run: free -h
      - run: df -h

  linux-arm:
    name: Linux ARM
    runs-on: ubuntu-24.04-arm
    steps:
      - run: lscpi
      - run: echo $PWD
      - run: free -h
      - run: df -h

  macos-13:
    name: MacOS 13
    runs-on: macos-13
    steps:
      - run: system_profiler
  macos-14:
    name: MacOS 14
    runs-on: macos-14
    steps:
      - run: system_profiler
